### Recuperar todas las películas

GET http://localhost:1234/movies

### Recuperar una película por id
GET http://localhost:1234/movies/11f07926-6582-354b-b277-00d86159fc7e

### Recuperar una película por género
GET http://localhost:1234/movies?genre=Action

### Crear una película con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}

### Actualizar una película
### !!! Como no validamos la id con zod no se modifica !!!
PATCH http://localhost:1234/movies/4e0153b4-19b7-f42f-b21a-8c760c211f97

{
  "id": "123", 
  "title": "Prueba",
  "year": 1998
}

### Borrar una película
DELETE http://localhost:1234/movies/43443c64-7b0a-924d-8d26-719b2a5a44e0