USE movies_db;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_NAME = 'movie_genres'
AND TABLE_SCHEMA = 'MOVIES_DB'
AND CONSTRAINT_TYPE = 'FOREIGN KEY';

ALTER TABLE movie_genres
DROP FOREIGN KEY movie_genres_ibfk_1;

ALTER TABLE movie_genres
ADD CONSTRAINT fk_movie_genres_movie_id
FOREIGN KEY(movie_id) REFERENCES movies(movie_id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE movie_genres
ADD CONSTRAINT fk_movie_genres_genre_id
FOREIGN KEY(genre_id) REFERENCES genres(genre_id)
ON DELETE CASCADE
ON UPDATE CASCADE;